language: c
script: asdf plugin-test imagemagick https://github.com/mangalakader/asdf-imagemagick.git 'identify -version'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
os:
  - linux
  - osx