name: "Imagemagick Plugin Test"

on:
  push:
    branches:
      - master

jobs:
  steps:
    - name: asdf_plugin_test
      uses: asdf-vm/actions/plugin-test@v1.0.0
      with:
        command: "convert --version"
