name: "Imagemagick Plugin Test"
on:
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          command: "convert --version"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GIT_TOKEN }}
